---
ansible_connection: network_cli
ansible_user: "srv_ansible"
ansible_password: "admin00"
#ansible_ssh_pass: "admin00"
ansible_network_os: "ios"
#IOS are store outside git repository. Please download it from cisco.com
ios_path: "../images/gold/"
...