---
all:
  hosts:
    localhost:
      ansible_python_interpreter: /usr/bin/python
  children:
    ngkit:
      children:
        isr1101:
          hosts:
            R1:
              ansible_host: 192.168.2.1
        ir1101:
          hosts:
            R2:
              ansible_host: 192.168.2.2
...
