---
all:
  children:
    ngkit:
      children:
        isr1101:
          hosts:
            R1:
              ansible_host: 192.168.2.3
        ir1101:
          hosts:
            R2:
              ansible_host: 192.168.2.4
...
