---
- name: "ROUTER >> Get Facts NGKIT Config"
  hosts: kit00001
  gather_facts: False
  tasks:
    - name: "SYS >> Set New IOS and reboot Task  for {{ ansible_net_model }}"
      ios_config:
        commands:
        - "no boot system"
        - "boot system bootflash:{{ ios_gold_file }}"
        - "no ip scp server enable"
        match: none
        save_when: always

    - name: "NET >> Reboot Router"
      ios_command:
        commands:
          - command: "reload"
            prompt: '[confirm]'
            answer: "\r"
   
    - name: "SYS >> WAIT FOR ROUTER TO RETURN"
      wait_for:
        host: "{{ ansible_host }}"
        port: 22
        delay: 120
      vars:
        ansible_command_timeout: 1800
      delegate_to: localhost
  
    - name: "SYS >> Gathering Facts..."
      ios_facts:
        gather_subset:
          - "!config"

    - name: "Assert that the IOS ver is correct"
      assert:
        that:
          - ios_gold_file == ansible_net_version